name: build & test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Validate checksum gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: "Set up JDK"
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: "Setup Gradle"
        uses: gradle/gradle-build-action@v2

      - name: Build
        run: ./gradlew build

